//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore1_mvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_mvcEntities : DbContext
    {
        public db_mvcEntities()
            : base("name=db_mvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<st> sts { get; set; }
        public virtual DbSet<tab_book> tab_book { get; set; }
        public virtual DbSet<tab_mvc> tab_mvc { get; set; }
    
        public virtual int sp_binsert(string na, string det, string pr, string uname, string psw)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var detParameter = det != null ?
                new ObjectParameter("det", det) :
                new ObjectParameter("det", typeof(string));
    
            var prParameter = pr != null ?
                new ObjectParameter("pr", pr) :
                new ObjectParameter("pr", typeof(string));
    
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pswParameter = psw != null ?
                new ObjectParameter("psw", psw) :
                new ObjectParameter("psw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_binsert", naParameter, detParameter, prParameter, unameParameter, pswParameter);
        }
    
        public virtual int sp_insert(string na, Nullable<int> ag, string addr, string em, string ph, string un, string ps)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var unParameter = un != null ?
                new ObjectParameter("un", un) :
                new ObjectParameter("un", typeof(string));
    
            var psParameter = ps != null ?
                new ObjectParameter("ps", ps) :
                new ObjectParameter("ps", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert", naParameter, agParameter, addrParameter, emParameter, phParameter, unParameter, psParameter);
        }
    
        public virtual int sp_blogin(string una, string psw, ObjectParameter status)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pswParameter = psw != null ?
                new ObjectParameter("psw", psw) :
                new ObjectParameter("psw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_blogin", unaParameter, pswParameter, status);
        }
    
        public virtual ObjectResult<sp_bprofile_Result> sp_bprofile(string na)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bprofile_Result>("sp_bprofile", naParameter);
        }
    
        public virtual int sp_bprofile_update(string una, string na, string det, string pr)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var detParameter = det != null ?
                new ObjectParameter("det", det) :
                new ObjectParameter("det", typeof(string));
    
            var prParameter = pr != null ?
                new ObjectParameter("pr", pr) :
                new ObjectParameter("pr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bprofile_update", unaParameter, naParameter, detParameter, prParameter);
        }
    
        public virtual int sp_bpswchange1(string uname, string oldpsw, string newpsw, ObjectParameter status)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var oldpswParameter = oldpsw != null ?
                new ObjectParameter("oldpsw", oldpsw) :
                new ObjectParameter("oldpsw", typeof(string));
    
            var newpswParameter = newpsw != null ?
                new ObjectParameter("newpsw", newpsw) :
                new ObjectParameter("newpsw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bpswchange1", unameParameter, oldpswParameter, newpswParameter, status);
        }
    }
}
