//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore1_mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_book
    {
        public int id { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public string price { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
